csci-499-fa24/Team1

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Added a pull request template that most likely will be updated over time

Created a pull request template

---

server/cron/storeRestaurants.js
server/models/inspections.js
server/models/locations.js
server/models/restaurants.js
server/package-lock.json
server/package.json
server/server.js

**Description**
This pull request contains the models necessary for handling inspection data from NYC Open Data API. These models allow for storing and managing restaurant inspection information such as inspection details, location, and the associated restaurant information
**What's in this change?**
- Inspection model: inspection related data is stored here, such as inspection date, actions, violations, etc
- Location model: location of the associated restaurant is stored here, such as geographical and administrative location data. 
- Restaurant model: Details about the restaurant is stored here and is connected with the inspection and location data with the camis column (id of restaurant)
- restaurants have a hasMany relationship with inspection data
- restaurants have a hasOne …

Models of the restaurant inspection data

---

.github/workflows/coverage.yml
server/controllers/example.js

Testing jest

---

.github/workflows/coverage.yml
server/test/example.test.js

Testing yml file

---

client/app/components/displayMap.js
client/app/globals.css
client/app/styles/displaymapfilter.css
client/package-lock.json
client/package.json
server/controllers/index.js
server/controllers/locations.js
server/test/locations.test.js

Description
Changed the entire map to use the google map javascript api instead of the embed api just so that I can display markers and the users location within a one mile radius. I also updated globals.css so that it doesnt show the black background and white text
displayMap.js: Displays the users location and all of the markers if you dont allow the users location or just the restaurants stored in database within a one mile radius. You can also click on a marker to view the name and address of the restaurant
globals.css: Just removed the black background and white text
locations.js: The backend logic code that takes in all of the latitude, longitude, address, name and id of each of the restaurants and displays it as json data
Used …

Diplays user location and markers and updated globals css

---

client/app/restaurants/[camis]/details.module.css
client/app/restaurants/[camis]/page.js
server/controllers/getRestaurantHours.js
server/server.js

Description
This PR improves the restaurant details page by refactoring how inspection data is displayed and adding functionality to fetch and display restaurant hours from an API.
1. Moved restaurant info (name, cuisine, address) outside the inspection boxes to prevent repetition.
2. Each inspection box now only shows grade, inspection date, and violations.
3. Display of open/closed status for the restaurant.
4. Added restaurant hours section that dynamically displays business hours for each restaurant.
5. Back button added for user navigation to the previous page.
6. Environment variables used for API URLs to fetch restaurant hours and inspection details.
7. Added route to fetch restaurant hours from the backend (server.js)
I tested locally and …

Inspection display

---

client/app/components/Events.js
client/app/components/Navbar.js
client/app/events/page.js
client/app/map/page.js
client/app/styles/Navbar.css
client/app/styles/events.css

Description
This event page displays upcoming Farmers' Markets and Street Festivals in NYC. It fetches data from the NYC Open Data API and provides filtering options based on borough, event type, date, and the events u can attend based on the time a user inputs.
- Fetches Farmers' Market and Street Festival events from the NYC Open Data API.
- Filters events by borough, event type (Farmers' Market, Street Festival), specific time, and date range.
- Adds pagination for a clean display of events.
- Displays events in a card layout with important details like event name, location, and times.
- Styling improvements for the event list, pagination, and filter form.
- Tested API calls to ensure proper fetching and filtering of event data.
- Verified that …

Event List Based on NYC Open Data API and styling

---

client/app/restaurants/[camis]/details.module.css
server/controllers/getRestaurantHours.js

Description
I made this pull request because after merging, we can't see the text of the inspection result, so I adjusted the color.
details.module.css: deleted the color.
I tested it locally.

Changed color styling for inspection display

---

client/app/components/displayMap.js
client/app/restaurants/[camis]/page.js
server/controllers/inspections.js

Description
It adds phone number display functionality to the restaurant detail page and updates the back button.
1. page.js: added phone number and improved back button.
2. displayMap.js: deleted "target="_blank" so it won't open a new tab
3. inspections.js: added 'phone' attribute.
I tested it locally and it works fine.

Reapplied changes: added phone number and fixed tab behavior

---

client/app/components/About.js
client/app/components/Home1.js
client/app/components/Navbar1.js
client/app/components/Testimonial.js

Description
Upload landing page modifications.
Added Sign up and Login buttons

Changes to Landing page.

---

client/app/components/Favorites.js
client/app/profile/page.js
client/app/styles/favorite.css
client/app/styles/profile.css

Description
fixed profile page css
modify profile page, profile.css, favorite.js, favorite.css

fixed profile page css

---

client/app/components/displayMap.js
client/app/profile/page.js

Description
Add Location Input, user map don't need to populate base of their current location. User can select location.
User control their location.

working map with search by location

---

client/app/components/displayMap.js

Description
Removed the adjusted coordinates code because of billing
displayMap.js - removed the adjusted coordinates code
Tested locally and it works fine

Removing adjust markers

---

README.md

Description
Updated readme
README.md : Updated postgresql instructions
Tested some markdowns

Updated installing postgreSQL instructions

---

client/app/components/displayMap.js

Get route of driving directions added to the map and icon to show and clean the route on the map.
Description
Add driving directions route on the map.
Click on the car icon to get driving directions from current location to selected location on the map.

Add driving directions

---

client/app/calendar/page.js
client/app/components/Events.js
client/app/components/MyCalendar.js
client/app/components/Navbar.js
client/app/components/PlaceDetails.js
client/app/components/PlaceDetailsCalendar.js
client/app/components/displayMap.js
client/app/styles/events.css
client/app/styles/mycalendar.css
client/package-lock.json
client/package.json
server/controllers/addPlan.js
server/models/user_plan.js
server/package-lock.json
server/package.json
server/routes/userPlanRoute.js

Description
created the calendar page
added new modules npm install
*MyCalendar.js component & Calendar Page*
* calendar shows the all user plans
* the user plans that are 'self events' have an onclick effect to display the place details
on the placedetails component
*CHANGES TO USER_PLANS MODEL/LOGIC*
* modified the user plans model to not require some of the properties and added 4 new properties pertaining to the NYC Events
* Updated the logic accordingly and created a Delete Plan
*New PlaceDetailsCalendar.js component*
* made a new PlaceDetailsCalendar.js component that is mostly forked of the place details but small changes to be more appropriate for the calendar (ie trash button). I made a new component that was copied of the other one because I didn't want to …

Modify user plan model

---

client/app/components/Sidebar.js
client/app/components/displayMap.js
client/app/styles/displaymapfilter.css
package-lock.json
package.json
server/controllers/getReviews.js

Description
This pull request implements a sidebar for displaying detailed restaurant information, including reviews, comments date, inspection results, restaurant hours, and website links.
Tested locally and verified that the sidebar displays all intended details correctly.

Add sidebar with reviews, date of comment, and website details

---

client/app/styles/mycalendar.css

Description
fixing css bug in the calendar
last time i swear

.css bug fix

---

client/app/components/displayMap.js

Option to show route using public transportation like train and bus are now available using the icon of the bus.
Description
Added option to show route to a restaurant or bar selected using public transportation service or bus icon.
Line 22: faBus for import the TRANSIT icon (VS Code put it automatically)
Line 103: declaration added for public transportation or TRANSIT option
Line 135: added due now are two travel mode available
Line 858~878: added the new button of the bus to select public transportation.

Add the use of public transportation option.

---

server/test/addPlan.test.js

Description
This pull request consists of a test file for user plans
addPlan.test.js: This file is the test file for the addPlan.js file. It checks everything from adding user plans, updating user plans, deleting user plans, and getting all user plans. 
N/A

Added test for user plan

---

client/app/components/Events.js
client/app/styles/events.css

Description
This pull request introduces a map to display the event's location and the user's location
- Removed Street Events as they are not related particularly related to food
- Added a map to the events page 
- The marker shows the user's current location by default
- A "Show Location" button is available for each event, which fetches the coordinates of the event location using the OpenCage Geocode API and displays it on the map.
Tested locally

Map for the events page with OpenCage geocoding API

---

.github/workflows/coverage.yml

Description
Updated the test coverage for dev branch
coverage.yml: Added dev branch for pull requests
N/A

Updated test coverage for dev

---

client/package-lock.json
client/package.json

Updated package-lock.json and package.json during modification of restaurant by name filter.
Description
Updated package.json and package-lock.json during modification of restaurant by name filter.
Update of package and package-lock files.

Update package-lock and package

---

client/app/calendar/page.js
client/app/components/EditTimeWindow.js
client/app/components/Events.js
client/app/components/Favorites.js
client/app/components/MyCalendar.js
client/app/components/PlaceDetailsCalendar.js
client/app/components/Settings.js
client/app/components/displayMap.js
client/app/events/page.js
client/app/globals.css
client/app/map/page.js
client/app/profile/page.js
client/app/settings/page.js
client/app/styles/mycalendar.css
client/app/styles/profile.css
client/package-lock.json
client/package.json

Description
add notifications and modified calendar page
- add notification to all pages that needs it
- calendar page - change the plans and events info container to a sidebar, both uses one sidebar
when you edit the time or remove the plan/event the change will reflect on the calendar immediately,
don't need to refresh to see the change

add notification and modified calendar page

---

client/app/components/Events.js

Description
This pull request increases the accuracy of the show event locations feature and also updated the show location button to an icon for more consistency
displayMap.js: fetching coordinates function has changed so you are finding the approximate coordinates from an intersection of two streets. Also changed the show location button to a fontawesome button just so it looks a bit better and more consistent with the add to plan button. Finally, the map will automatically recenter to whatever marker is showing right now
I tested through localhost and console logs

Fixed event locations

---

client/app/components/displayMap.js
client/app/styles/displaymapfilter.css
package-lock.json
package.json

Description
This pull request introduces a new feature that allows filtering by inspection results (e.g., A, B, C, or Ungraded). It also improves the layout and styling of the filter dropdowns for better usability.
Verified that Filter by Inspection Result works as expected.
Tested on both desktop and mobile views for proper alignment and responsiveness.

added filter by inspection and changed the filter style a little bit

---

client/app/calendar/page.js
client/app/components/Loading.js
client/app/events/page.js
client/app/map/page.js
client/app/profile/page.js
client/app/settings/page.js
client/app/styles/loading.css

Description
This pull request introduces a loading screen for the pages
Icon Design: Includes a fork and knife animation using Font Awesome.
Progress Bar
Tested Locally

Loading Screen

---

client/app/components/displayMap.js

Update default message in search bar by restaurant name to All.
Description
Update default message in search bar Restaurant by name filter.
Just change the message to All.

Update Search bar in displayMap.js

---

client/app/profile/page.js
client/app/styles/profile.css
client/package-lock.json
server/controllers/addPlan.js
server/test/addPlan.test.js

Description
fixed duplicate events and profile page responsiveness
addPlan.js - added a check for duplicate event
profile page - fixed up the page responsiveness
test locally

Duplicate events/profile responsive

---

client/app/App.css

The Login and Sign up buttons now can be visible on a smartphone screen. The landing page was centered and aligned when using the add from a smartphone.
Description
Tha landing page is now responsive when using the app on a smartphone. Login and Sign up buttons are now visible on a smartphone screen.
Modified App.css to centered elements and buttons when using the app on asmarphone screen.

Landing page is responsive on smartphones.

---

client/app/components/Events.js
client/app/styles/events.css

Description
This PR introduces responsive styling for event layout and filter forms to ensure an optimal user experience across different screen sizes
- Flexbox adjustments to dynamically switch between row and column layouts based on screen width.
- Improved styling for buttons and icons to ensure proper alignment and usability on small devices.
- Updates to the filter form, including padding, font sizes, and spacing for better readability.
- Multiple media queries targeting different screen ranges to ensure smooth responsiveness.
Tested layout changes on various screen sizes to ensure elements adjust correctly for the following breakpoints:
- Small screens (< 500px)
-  Mid-range screens (500px - 850px)
- Larger screens (> 850px)

Responsive Styling for the Events Page

---

client/app/components/Contact.js
client/app/components/Footer.js
client/app/components/Navbar1.js

Navbar, contact and footer sections modified after review feedback from users.
Description
Landing page Navbar buttons, Contact email link and Footer section has been modified.
Login and Sign up buttons once user login are replaced for Profile(Main menu) and Logout buttons. email contact button in Contact secction now is working and Footer section was modified.

Modify landing page.

---

client/app/App.css

Style modified for landing page.
Description
Style for landing page has been modified.
Navbar, Contact and Footer section style has been modified for landing page.

Style for landing page was modified.

---

client/app/App.css

Text in landing page is now white due new testing background and Profile text button now is white also.
Description
Style for text was changed to white color.
Profile button text and titles and paragraphs in landing page are now white color.

Letters changed to wthite color.

---

client/app/components/MyCalendar.js
client/app/components/PlaceDetailsCalendar.js
client/app/styles/mycalendar.css

Description
This pull request consists of an updated UI and responsiveness of the calendar page. I changed the whole layout of the calendar, as well as the key and modified the styling of all of the components in the page. Also I made sure to have the size of the place details side bar and the newly added key sidebar adjust based of the width of the screen size. 
MyCalendar.js:Consists of new code for the new key sidebar
mycalendar.css: Consists of the media queries for responsiveness, and some modifications to some font sizes, widths, and added new sidebar code
PlaceDetailsCalendar.js: removed some height styles for the icons for responsiveness
Tested locally with different screen sizes

Updated calendar page responsiveness and UI

---

client/app/components/Events.js
client/app/components/displayMap.js
client/app/styles/events.css

Description
This PR enhances the styling of the events card to improve readability and responsiveness across various screen sizes.
Card Layout Adjustment:
o Displays two cards per row on larger screens for a better layout.
o Uses a single large card per row on smaller screens to improve readability and presentation.
-[x]Added responsiveness for all screen sizes, ensuring the cards adapt smoothly; Ensured markers align correctly when two events are displayed per row on larger screen sizes.
-[x] Applied box shadow to the cards for better visual depth and separation.
Verified that the layout is responsive on different screen sizes.
Ensured proper alignment and display of elements

Nyc Events Styling and Responsiveness
